name: medyaatlas
description: MedyaAtlas — Windows, Android ve web GPS medya haritası (yerel kayıt).
publish_to: 'none'
version: 1.0.50+78

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.6.0
  image_picker: ^1.1.2
  exif: ^3.3.0
  file_picker: ^8.3.7
  path: ^1.9.1
  web: ^1.1.1
  intl: ^0.20.2
  http: ^1.2.2
  desktop_drop: ^0.7.0
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  permission_handler: ^12.0.1
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  photo_manager: ^3.7.1
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  archive: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
